version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  api:
    container_name: nestjs-prisma
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./code:/app
    environment:
      API_NAME: nestjs-prisma
      API_PORT: 3000
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/database?schema=public"
      LOGGER: "debug,error,log,verbose,warn"
      NODE_ENV: "development"
    depends_on:
      - database
